name: Integration tests - PR
run-name: (PR - ${{ github.head_ref }} -> ${{ github.base_ref }}) - Integration testing

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  pr-integration-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
