name: Unit test - PR
run-name: (PR - ${{ github.head_ref }} -> ${{ github.base_ref }}) - Unit testing

on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
#  pr-unit-testing:
#    runs-on: ubuntu-latest
#    container: ghcr.io/cirruslabs/flutter:latest
#    steps:
#      - uses: actions/checkout@v4
#
##        // run dart build runner
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Run Unit Tests
#        run: flutter test --file-reporter "json:tests/json"
#
#      - name: Archive test results
#        uses: actions/upload-artifact@v3
#        if: always()
#        with:
#          name: test-results
#          path: tests/json

  pr-integration-testing:
#    needs: pr-unit-testing
    runs-on: ubuntu-latest
#    container: ghcr.io/cirruslabs/flutter:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: flutter pub get

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          arch: x86_64
          profile: Nexus 6
          script: ./gradlew connectedCheck
